### PR TITLE
fix: improved incorrect vote tally

### LINKED ISSUE #402: Error: Voting consensus process issues
I run two `ACTIVE` Oracles, and I've been trying to register a new Oracle.

Registration and voting were all performed normally.

However, the voting results were different than expected.

Below is the query result for voting.
```
> panacead q oracle oracle-registration ...
oracle_registration:
  address: panacea1krz4vq92r4gyqt50d0sw2qwedutn0lnl036ckc
  encrypted_oracle_priv_key: null
  node_pub_key: As0i8Bv+8gNbxZxI/yla1j2tpXLjMOki4dRnoWfOcSF8
  node_pub_key_remote_report: AQAAAAIAAAD...
  status: ORACLE_REGISTRATION_STATUS_REJECTED
  tally_result:
    consensus_value: null
    invalid_yes:
    - consensus_value: S7AnWJtPgouG7RgGl3GVDgLKACBX2R1nEzrPIdirqxumGMOoOcUjBh4wkxKw2+Vrut+uKAAg3SAeCqJ7rvQbiPdNKI9Dub7eqWUU8fDKMqETRHT5yQBZmSZ2JIZlA1yUnpVzjJS8J8ZOT+i2L+jWUeKMwz8fcT3NN4z7uB+RX0s6WqrOhKPE6oS35hRkulXrHFAzooVmLC70ovzLsxGgMDqC0SHiQQ==
      voting_amount: "1000000000"
    - consensus_value: S7AnWJtPgouG7RgGl3GVDgLKACBX2R1nEzrPIdirqxumGMOoOcUjBh4wkxKw2+Vrut+uKAAg3SAeCqJ7rvQbiPdNKI9Dub7eqWUU8fDKMqETRHT5yQBZmSZ2JIZlA1yUnpVzjJS8J8ZOT+i2L+jWUeKMwz8fcT3NN4z7uB+RX0s6WqrOhKPE6oS35hRkulXrHFAzooVmLC70ovzLsxGgMDqC0SHiQQ==
      voting_amount: "1000000000"
    "no": "0"
    total: "2000000000"
    "yes": "0"
  trusted_block_hash: 0iEJciMfOpC/o7S+dWl34apWoMKMOAQxtQ9fd7c7GYI=
  trusted_block_height: "153"
  unique_id: f1370ae739da9de8b073b9ce7347eacb6ed00998e1cdf52fdf14f09df165604a
  voting_period:
    voting_end_time: "2022-09-13T07:31:15.165887691Z"
    voting_start_time: "2022-09-13T07:30:45.165887691Z"

```

The same consensus_value came out, but the vote did not passed

### PR DESCRIPTION
**Pull request by gyuguen**
Close #402 

Fixed ConsensusValue always being fixed to the last value in the Array.

### CODE REVIEW

File: x/oracle/keeper/tally.go [hunk 1]
```diff
@@ -18,18 +19,20 @@ func (k Keeper) Tally(ctx sdk.Context, voteIterator sdk.Iterator, voteType types
 	k.setOracleValidatorInfosInTally(ctx, tally)
 
 	for ; voteIterator.Valid(); voteIterator.Next() {
+		vote := reflect.New(reflect.ValueOf(voteType).Elem().Type()).Interface().(types.Vote)
```
Comment (gyuguen) [inline x/oracle/keeper/tally.go:22]: I'm not sure if this is the best way to copy the interface. 🤔

**Review by H4NLee — APPROVED** [review]
LGTM!

File: x/oracle/keeper/tally.go (hunk 1 above)
Comment (youngjoon-lee) [reply x/oracle/keeper/tally.go:22]: I understood what you tried to do. This will work, but I think that reflection codes are hard to read. It can cause mistakes in the future. 
So, I'd suggest a simpler way: https://github.com/medibloc/panacea-core/commit/e1e6328cd87221f83ba60a4d014252409b0683fe.

Comment (gyuguen) [reply x/oracle/keeper/tally.go]: Thank you!
I fixed it. (https://github.com/medibloc/panacea-core/pull/403/commits/9cbdc8929f9a81333c6cae92cf6e071a749476b2)

**Review by youngjoon-lee — APPROVED** [review]
lgtm
